// Bundled Leaflet + plugin library contents, as plain JS string exports
// (see assets/leaflet-vendor/*.const.js, generated by
// scripts/convert-leaflet-assets.js). Loading these locally instead of
// from unpkg.com removes the network round-trip + re-parse cost that
// was happening on every WebView reload.
//
// These are plain `import` statements — no Asset.fromModule, no Metro
// asset registry involved. Metro bundles these exactly like any other
// JS source file in your project, which is inherently reliable.
import leafletJs from "../assets/leaflet-vendor/leaflet.js.const.js";
import leafletCss from "../assets/leaflet-vendor/leaflet.css.const.js";
import markerClusterJs from "../assets/leaflet-vendor/leaflet.markercluster.js.const.js";
import markerClusterCss from "../assets/leaflet-vendor/MarkerCluster.css.const.js";
import markerClusterDefaultCss from "../assets/leaflet-vendor/MarkerCluster.Default.css.const.js";
import leafletRotateJs from "../assets/leaflet-vendor/leaflet-rotate.js.const.js";

// No async loading needed anymore — these are just JS string constants,
// available synchronously as soon as the module is imported.
export function loadMapAssets() {
  return {
    leafletJs,
    leafletCss,
    markerClusterJs,
    markerClusterCss,
    markerClusterDefaultCss,
    leafletRotateJs,
  };
}